version: '3.8'
services:
  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_DB: freelancePlatformDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d freelancePlatformDb"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    depends_on:
      postgresdb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/freelancePlatformDb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8090:8090"
    volumes:
      - ./logs:/app/logs  # ← Volume для логов приложения (опционально)
      - ./uploads:/app/uploads  # ← Volume для загружаемых файлов (опционально)

volumes:
  postgres_data:  # ← Объявление named volume
    driver: local